Enable build for aarch64 in Dockerfile
jbarlow83/OCRmyPDF pull request #564
Opened 2020-05-24 18:06 UTC by andkrause

This PR contains an "enhanced" version of the original Dockerfile that enables you to build cross-platform images for both amd64 and aarch64 with buildx. Sample command is below.

`docker buildx build --push --platform linux/arm64/v8,linux/amd64 --tag jbarlow83/ocrmypdf:latest --file .docker/Dockerfile .`

I will also try to work on a matching action to automate build upon merge.

2020-05-25 05:44 UTC, jbarlow83 commented
A few questions:

Is the issue just that those dependencies are not explicit?

I currently have Docker Hub set up to auto-build ocrmypdf whenever there's a new commit to master or tagged version. How would that work in this brave new world that acknowledges architectures other than x64? Is the idea that we'd have a Github Action or Azure Pipeline build step to generate and push the images, or can Docker Hub do that?

Does that buildx command generate two images, one for arm64 and one for amd64?

2020-05-25 12:12 UTC, andkrause commented
The underlying issue is that precompiled wheels / dependencies are not available for aarch64. Hence I had to add several dependencies (mostly based on other issues associated to this repo) to allow pip to compile the respective modules. Now the Dockerfile can be used for docker build on both amd64 as well as aarch64 architectures. 

This also enables the outlined multi-architecture build (with buildx). In essence this means that 2 images will be built under the same tag. The docker daemon knows its underlying cpu architecture and will then pull the image matching its architecture. The details are really well described [here](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/). I have used it to locally build this [clone](https://hub.docker.com/repository/docker/andy008/ocrmypdf/tags?page=1) of ocrmypdf with docker desktop for mac.

A real setup would of course use a CI/CD approach. Both Docker Hub and Github Actions seem to support this. I was going to explore github actions and could contribute a workflow later on. 

Hope that covers your questions. Please share your thoughts.

2020-05-27 10:08 UTC, jbarlow83 commented
I see, thanks for the explanation.

I'm currently using Azure Pipelines but Github Actions would be fine, since I will probably migrate everything there. Better to have one CI do it all in one shot.

2020-05-31 19:33 UTC, andkrause commented
@jbarlow83: Github Workflow to execute buildx is now included. To use it, the following Github secrets need to be maintained:

- DOCKERHUB_IMAGE_NAME = ocrmypdf
- DOCKERHUB_USERNAME = jbarlow83
- DOCKERHUB_PASSWORD = Docker hub password (or [Token](https://docs.docker.com/docker-hub/access-tokens/)) 

Workflow is triggered upon push to master branch (latest tag) or release creation (release-name tag). It takes around 2 hours to complete.

Let me know if you have further questions.

2020-06-12 04:04 UTC, jbarlow83 commented
I will accept this, just hesitating on the "2 hours to complete" aspect. That's... lengthy.

2020-06-12 13:29 UTC, andkrause commented
I was surprised as well, I basically see 2 reasons for it:

* Github does not really provide a lot of CPU (on my Macbook the entire thing takes 15 minutes)
* A lot of the requirements are not available as binaries for aarch64 and hence they are compiled at runtime. As my python is non-existant I have no idea how to fix it.

Cheers

Andreas

2020-06-22 21:54 UTC, QuLogic commented
Are you building wheels, or a container? Because these dependencies may not be available as pre-compiled wheels for those architectures, but they may already be compiled in the distro (e.g., Fedora has all of your deps for aarch64, and I'm sure Debian does too.)

2020-06-22 22:13 UTC, jbarlow83 commented
This is a container build, but as currently written the Dockerfile uses PyPI wheels to satisfy many of the dependencies, rather than the operating system's.

If someone just want container isolation of an OS version, they can write a trivial Dockerfile to `dnf install ocrmypdf`.

If someone upgrade ocrmypdf beyond the OS version, using the OS version of everything else, `pip install --user ocrmypdf` should cover them.

So the use case of the ocrmypdf Docker image is for people who want more recent versions of dependencies than their OS may provide (or jbig2enc which is not distributed because of its lingering patent fears), which I think justifies using Python wheels as we do in the Docker image.

Definitely the best way to get a non-x86 ocrmypdf right now is to use a pre-compiled distro.

2020-08-14 05:40 UTC, andkrause commented
@jbarlow83: is there any hope this will be merged any time soon?

2020-08-28 23:36 UTC, jbarlow83 commented
The project license has changed since you submitted this PR. Are you okay with the new license?

2020-08-29 10:19 UTC, andkrause commented
works for me

2020-09-09 17:59 UTC, 0x326 requested changes

2020-09-09 17:59 UTC, 0x326 commented on .docker/Dockerfile
> +  git
There shouldn't be a trailing white space character here
```suggestion
  git
```

2020-09-09 17:59 UTC, 0x326 commented on .docker/Dockerfile
> +  libxslt1-dev \
When I added `aarch64` support on my own, I only needed:
```
  libffi-dev \
  libqpdf-dev \
  python3-dev \
```
However, adding more probably won't hurt

2020-09-09 17:59 UTC, 0x326 commented on .github/workflows/buildx-latest.yml
> +            --file .docker/Dockerfile .
Missing ending newline

2020-09-09 17:59 UTC, 0x326 commented on .docker/Dockerfile
> +  libxslt-dev \
Is this needed? I didn't need it when I built `v11.0.2`

2020-09-09 17:59 UTC, 0x326 commented on .docker/Dockerfile
> +  && rm -rf /var/lib/apt/lists/*
Nice addition, but unrelated to `aarch64` support

2021-04-06 09:07 UTC, closed without merging